### PR TITLE
Please update strings.xml SK

### PR DESCRIPTION
**Pull request by ja-som**

### CODE REVIEW

**Comment by rignaneseleo** [comment]
please update the new strings.xml.
You can try my [webtool](http://stringsxmlbuilder.netsons.org/builder.php?originalXmlURL=https://raw.githubusercontent.com/rignaneseleo/SlimSocial-for-Facebook/master/SlimFacebook/app/src/main/res/values/strings.xml&translationLang=sk)

**Comment by ja-som** [comment]
I´m sorry, but no, I'm not interested anymore. I see that "R3nd0gg" used webtool and he fucked up my translation.

**Comment by rignaneseleo** [comment]
what do you mean? there are some typo?

**Comment by ja-som** [comment]
Mostly incorrect grammar, sentences do not make sense, it looks as from really bad translation machine.

**Pull request closed without merging**
